version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: tna0y/corporate-directory
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build & Test Docker image
          command: |
            docker build -t $IMAGE_NAME:$CIRCLE_BRANCH .
      - run:
          name: Push Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $IMAGE_NAME:$CIRCLE_BRANCH

